{
 "title": "Redis",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Group",
    "query": {}
   },
   { "name": "Hosts", "query": "$Group.*" },
   {
    "name": "Database",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Redis Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: Ping" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: Redis mode" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: Redis version" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Cluster Enabled",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: Cluster enabled" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: Uptime" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Fragmentation ratio",
   "type": "stat",
   "description": "This ratio is an indication of memory mapping efficiency:\n— Value over 1.0 indicate that memory fragmentation is very likely. Consider restarting the Redis server so the operating system can recover fragmented memory, especially with a ratio over 1.5.\n— Value under 1.0 indicate that Redis likely has insufficient memory available. Consider optimizing memory usage or adding more RAM.\n\nNote: If your peak memory usage is much higher than your current memory usage, the memory fragmentation ratio may be unreliable.",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Redis: Memory fragmentation ratio"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "AOF last write status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: AOF last write status" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "AOF current rewrite time sec",
   "type": "stat",
   "description": "Duration of the on-going AOF rewrite operation if any",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Redis: AOF current rewrite time sec"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis: AOF last rewrite time sec",
   "type": "stat",
   "description": "Duration of the last AOF rewrite",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Redis: AOF last rewrite time sec"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Redis role",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: Replication role" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RDB last bgsave status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: RDB last bgsave status" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RDB current bgsave time sec",
   "type": "stat",
   "description": "Duration of the on-going RDB save operation if any",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Redis: RDB current bgsave time sec"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RDB last bgsave time sec",
   "type": "stat",
   "description": "Duration of the last bg_save operation",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Redis: RDB last bgsave time sec"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Slave connecteds",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: Connected slaves" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Clients connected",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: Connected clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Clients blocked",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: Blocked clients" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU utilization in %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent", "label": "CPU usage %" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: CPU utilization" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU time utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "CPU time req" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/CPU sys/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/CPU user/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes", "label": "RAM Usage" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Redis: Memory us/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes", "label": "Network I/O Bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Redis: Instantaneous input bytes per second"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": {
      "filter": "Redis: Instantaneous output bytes per second"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Expiration/evicted ratio",
   "type": "graph",
   "description": "Number of evicted keys due to maxmemory limit & Total number of key expiration events",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Expiration/evicted ratio" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: Evicted keys" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: Expired keys" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Dictionary hit ratio",
   "type": "graph",
   "description": "Number of successful lookup of keys in the main dictionary\nNumber of failed lookup of keys in the main dictionary",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Hit ratio" }
   ],
   "targets": [
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: Keyspace hits" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Redis" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "Redis: Keyspace misses" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 32 },
   "options": {
    "content": "<h1 class=\"text-center\">$Database</h1>"
   },
   "content": "<h1 class=\"text-center\">Host checking: $Hosts</h1>",
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Average TTL Expiration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "$Database" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "DB db0: Average TTL" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Total keys",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short", "label": "Total keys" }
   ],
   "targets": [
    {
     "application": { "filter": "$Database" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Keys/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "$Database" },
     "group": { "filter": "$Group" },
     "host": { "filter": "$Hosts" },
     "item": { "filter": "/Expires/" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}